name: search_and_stay
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^3.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  http: ^0.13.5
  flutter_speed_dial: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: any
  flutter_launcher_icons: any

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: images/logoSplash.png
  color: ff5313
  android_disable_fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#F8F8FF"
  adaptive_icon_foreground: "images/icon-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/logoSplash.png
    - images/logo.png
    - images/search_and_stay.png
    - images/no_image_icon.png